name: Demo 2

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master
      - 'feature/**'
#  workflow_dispatch:

jobs:
  run-regression-tests:
    name: Uruchom co≈õ w kontenerze
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: ghcr.io/lekcyjna123/wykladgitdemo:w2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Wypisz informacje
        shell: bash
        run: |
          uname -a
          cat /etc/os-release 
